#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys
import os

from lib import i18n
from daemon import main as BillReminderd

def main():
    help = _("""Usage:  billreminderd [OPTIONS...]

Options:
  --help, -h, -?\tShow this message.
  --verbose\t\tPrint output messages.
  --no-daemon\t\tDon't run as a daemon.
  --open-gui\t\tStart daemon and launch GUI.
  --version, -v\t\tDisplays the version number for this application.
""")

    # Verify arguments
    args = sys.argv
    if '--help' in args or '-h' in args or '-?' in args:
        print help
        raise SystemExit
    elif '--version' in args or '-v' in args:
        print _('This is %(appname)s - Version: %(verion)s') % \
                                      {'appname': '%s Daemon' % common.APPNAME,
                                       'version': common.APPVERSION}
    else:
        BillReminderd.main()

if __name__ == "__main__":
    main()
