#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys
import os

try:
    import gtk
except ImportError:
    print "Please install gtk"
    raise SystemExit

try:
    import pygtk
    pygtk.require("2.0")
except ImportError:
    print "Please install pygtk"
    raise SystemExit

try:
    from lib import i18n
    from gui.maindialog import MainDialog as BillReminder
    import lib.dialogs
    import lib.common
except ImportError, e:
    print str(e)
    raise SystemExit

help = _("""Usage:  billreminder [OPTIONS...]

Options:
  --help, -h, -?\tShow this message.
  --about\t\tAbout this application.
  --add\t\t\tAdds a new record to the database.
  --standalone\t\tAccess database directly, without daemon.
  --version, -v\t\tDisplays the version number for this application.
""")


def main():
    args = sys.argv

    if "--help" in args or "-h" in args  or "-?" in args:
        print help
    elif "--about" in args:
        lib.dialogs.about_dialog()
    elif "--add" in args:
        print lib.dialogs.add_dialog()
    elif "--version" in args or "-v" in args:
        print _("This is %(appname)s - Version: %(version)s") % (lib.common.APPNAME, lib.common.APPVERSION)
    else:
        gtk.gdk.threads_init()
        app = BillReminder()
        gtk.main()

if __name__ == "__main__":
    main()
